import { NextResponse } from "next/server";
import { headers } from "next/headers";

/** Return Authorization header from request (auth proxy). Same-origin only. */
export async function GET() {
  const headersList = await headers();
  // const authorization = headersList.get("authorization");
  const authorization = "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJQSjJmangyTzgzeGhHc3VmU3M2LVRvWUhZa01xY2RoX2JJRHFOS0hwdXhnIn0.eyJleHAiOjE3NzI2MDg3MjQsImlhdCI6MTc3MjYwODQyNCwianRpIjoiMTZjNmNlNmEtMmRhNS00NmUzLTg5YTgtMzRkMjg4YjM3MDQ3IiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5tb25leW1hbi5ydS9hdXRoL3JlYWxtcy9NTVJVIiwiYXVkIjoiYXV0aC1zZXJ2aWNlLW1tcnUiLCJzdWIiOiJkM2U5MjRmNy1hNTc2LTQyOTAtOWY4MC1jZDI5ZDk5YjRjNTAiLCJ0eXAiOiJJRCIsImF6cCI6ImF1dGgtc2VydmljZS1tbXJ1Iiwibm9uY2UiOiIwQjRob09XUTg5Ri16allkam9RWFFXVE0wNHBWRUVIaGg5M3M3YThlNVFZIiwic2lkIjoiNTgyNjUwM2QtMDA3ZS00ODllLWFlZjQtOTJiMDM5ZWUyMWM1IiwiYXRfaGFzaCI6Im4tcHBRbjJNaHVaSjA1NFJoVnc4VkEiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6Ik9sZWcgU2F2a28iLCJncm91cHMiOlsicmVkcGFuZGEtcm9sZSIsImVsZW1lbnRhcnktcm9sZSIsImRlZXAtYWdlbnQiLCJhdXRoLXJvbGUiLCJmbG93ZXItZHdoLXJvbGUiLCJldmlkZW50bHktcm9sZSIsInJlZHBhbmRhLWludGVncmF0aW9uLXJvbGUiLCJraWJhbmEtcm9sZSJdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJvbGVnLnNhdmtvQG1vbmV5bWFuLnJ1IiwiZ2l2ZW5fbmFtZSI6Ik9sZWciLCJmYW1pbHlfbmFtZSI6IlNhdmtvIiwiZW1haWwiOiJvbGVnLnNhdmtvQGlkZmluYW5jZS5jb20ifQ.x1L-3iCKl5lwTFSmtQPHO-7HUI3WBhetGrqXQ8mGcyXX9KTYBUOb9_omIVUYn8nwCuN2RbcXA1-CikOw9b9_HSOMluDH9pQfPrwSzLrSxdZBmIsoV90PKICiC1UusFy-7sPijZ1IXpZF-cHQAWm2B1j2CrYLlbBL5uAF4XQQY_UDyGumy25JleGvmnrDE-wsqJIaiYKPHzSaiNlPpfCgqwLfz3L-4Lis2QC8dzcibn2g5NirmMv03e5PlG8pZsznDY22EPQJ4RqrK0KOvTV8_WUkUyyAw6lCEuAe6qsCRC_TqVXYvj9yBAPzQN6WRQdKYady1iXbi5xg7z9lcVwg1A";
  return NextResponse.json({ authorization: authorization ?? null });
}
